# Generated by Django 3.1.7 on 2021-09-04 16:55

from django.db import migrations, models
from imdb import IMDb


def seed_db(apps, schema_editor):
    # Get filmography model schema
    Filmography = apps.get_model('uncaged_app', 'Filmography')

    # Create an instance of the IMDb class
    ia = IMDb()

    # Get info for Nic Cage
    nic = ia.get_person('0000115')

    # # Get info for each Nic Cage movie
    for movie in nic['filmography']['actor']:
        # Get IMDb movie ID
        id = movie.movieID

        # Retrieve movie data 
        current = ia.get_movie('9624766')
        ia.update(current, info=['main', 'plot', 'vote details'])
        # print(current.infoset2keys)
        cast_i = 0
        while str(current['cast'][cast_i]) != 'Nicolas Cage':
            cast_i += 1

        title = str(current['title'])
        year = str(current.get('year', 'TBA'))
        role = str(current['cast'][cast_i].currentRole)
        coverURL = current.get('cover url', 'TBA')
        plot = current.get('plot', 'TBA')
        runtime = current.get('runtimes', 'TBA')
        imdb_rating = current.get('arithmetic mean', 'None')

        if runtime != 'TBA':
            if 'movie' in str(current['kind']).lower():
                runtime = runtime[0] + ' minutes'
            else:
                runtime = 'Varies by episode'

        Filmography.objects.create(imdb_id=id, title=title, year=year, role=role, 
            imdb_rating=imdb_rating, runtime=runtime, plot=plot, cover_url=coverURL)


class Migration(migrations.Migration):

    dependencies = [
        ('uncaged_app', '0003_auto_20210904_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmography',
            name='cover_url',
            field=models.URLField(null=True),
        ),
        migrations.RunPython(seed_db)
    ]
