# Generated by Django 3.1.7 on 2021-09-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncaged_app', '0003_auto_20210904_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmography',
            name='cover_url',
            field=models.URLField(null=True),
        )
    ]
